### ISSUE TITLE
Output in batch mode includes log messages

### ISSUE THREAD

**Issue by TanguyPerson** [egobillot/calltop#19]
**Description**

When using batch mode, output includes log messages in addition to expected data.
It could confuse output parsing and make integration more difficult.

I've noticed erorr messages and more informal messages as well

**To Reproduce**
1. Run calltop in batch mode: 'sudo timeout 30 ./calltop.py -b > /tmp/calltop.out'
2. Look at output, in particular its beginning

**Expected behavior**
Output only contains data, each batch separated with an empty line.
Not error or other information messages.
Error messages should be sent to stderr.

**Actual behaviour**
Error/info messages at the beggining of the file:
head /tmp/calltop.out 
Failed to attach to kprobe b'__x64_sys_all'
b'Collecting first data ...'
   Pid     Process name             Function     latency(us)          Call/s           Total
   569         chromium                 read               0               1               1
   569         chromium                 poll               0               3               3

**Environment**
 - kernel: Linux 5.6.2-arch1-2 #1 SMP PREEMPT x86_64 GNU/Linux
 - Distrib: Archlinux x86_64, stable 
 - Version or revision: git clone, 8ee86542b509a502f3ef909de5f1164c13cdf9d6
 - package dependencies version:  bcc 0.13.0-1, bcc-tools 0.13.0-1, python-bcc 0.13.0-1

**Additional context**
Maybe the best solution would be to add an option parameter for batch output, to be able to send it to a file.
And at least, to redirect all errors and info messages to stderr (?)

**Comment by egobillot** [comment]
seems to be fixed now. I close the ticket.
