### ISSUE TITLE
key [f] mapped for dynamic filter is not documented 

### ISSUE THREAD

**Issue by TanguyPerson** [egobillot/calltop#20]
**Describe the bug**
It is apparently possible to dynamically filter while using calltop in interactive mode.
But how to use it is hard to guess ! I discovered (by error) that if was the F key.

**To Reproduce**
1. Run calltop in interactive mode: 'sudo ./calltop.py -l'
2. Look for keymapping on last line
3. Quit and look for key binding in embeded help: './calltop.py -h'
4. Look for documentation: 'cat README.md'

**Expected behavior**
2. Key mapped for filtering is listed in the bottom line

**Actual behaviour**
2. Key mapped for filtering is listed in the bottom line, as other keys mapped to other actions
3. Nothing about key mapping
4. Nothing about key mapping

**Environment**
 - kernel: [i.e uname -a output]
 - Distrib [e.g. ubuntu 18.10, Debian 9]
 - Version or revision : git clone, 8ee86542b509a502f3ef909de5f1164c13cdf9d6
 - package dependencies version [i.e bpfcc-tools version

**Additional context**
I may not be relevant to document everywhere, but at least once, and in a consistent way wrt other mapped keys.

**Comment by egobillot** [comment]
Now in the readme and updated in the bottom line ac0a56f8794576c6521647ae74050a7f68d68db3
