### ISSUE TITLE
[BUG] Sorting options are confusing and too limited

### ISSUE THREAD

**Issue by TanguyPerson** [egobillot/calltop#23]
**Describe the bug**
Interactive mode provides a way to sort based on different criteria.
But its seems very limited and seems to work in a quite confusing way.

**Expected behavior**
It should be possible to change and choose *ascending or descending sort*.

**Additional information**
When sorting by "total count" or by "Call/s", resulting order does not seem to be very logic.

It seems to me that process are first ordered by the total calls (all functions summed up), which is value that is not shown ! Maybe you should add a "process summary" line for each process ?

Even though the order seems wrong to me (?). I would expect that, for each process, lines are ordered by descending call/s or total, but it is apparently not the case.

So it is unclear whether *sort* applies to processes, functions for each process, or both (somehow).

**Comment by egobillot** [comment]
fixed by dc9708bce7e404c05781a76720d731de8602ddf8.
You can now use the '<' and '>' key to select stat sort criteria.
You can now use the right and left arrow key to select doc (per process) sort criteria.
